# -*- coding: utf-8 -*-
from pathlib import Path

def read_file(path):
    try:
        return Path(path).read_text(encoding="utf-8").strip()
    except Exception as e:
        return f"(file not found: {e})"

files = {}
for name, src in [
    ("telegram_publisher", "docs/raw/telegram_publisher.txt"),
    ("image_prompt_engine", "docs/raw/image_prompt_engine.txt"),
    ("image_engine", "docs/raw/image_engine.txt"),
    ("asset_manager", "docs/raw/asset_manager.txt"),
    ("telegram_engine", "docs/raw/telegram_engine.txt"),
    ("auto_telegram_pub", "docs/raw/auto_telegram_publisher.txt"),
    ("vk_publisher", "docs/raw/vk_publisher.txt"),
    ("runner", "docs/raw/runner.txt"),
    ("image_job", "docs/raw/image_job.txt"),
    ("jobs_init", "docs/raw/jobs_init.txt"),
    ("asset_orm", "docs/raw/asset_orm.txt"),
    ("content_orm", "docs/raw/content_orm.txt"),
    ("channel_orm", "docs/raw/channel_orm.txt"),
    ("main_py", "docs/raw/main_py.txt"),
    ("docker_compose", "docs/raw/docker-compose.txt"),
    ("db_stats", "docs/raw/db_stats.txt"),
    ("workflows", "docs/raw/workflows.txt"),
    ("file_list", "docs/raw/file_list.txt"),
]:
    files[name] = read_file(src)

L = []
def a(s=""): L.append(s)
def code(title, key, lang="python"):
    a(f"### {title}")
    a("")
    a(f"`{lang}")
    for line in files[key].split(chr(10)):
        a(line)
    a("`")
    a("")

a("# AI MEDIA FACTORY - Extended Master Documentation")
a("")
a("**Version:** 1.12.0")
a("**Last Update:** 2026-08-11")
a("**Status:** Sprint 11 Complete (Multi-Platform Publishers + Image Domain)")
a("")
a("> Этот документ содержит РЕАЛЬНЫЙ КОД всех критических компонентов.")
a("> Любой новый чат/разработчик сможет продолжить работу без повторения ошибок.")
a("")
a("---")
a("")

a("## 1. Vision & Philosophy")
a("")
a("AI Media Factory - автономная платформа производства контента.")
a("Канал создаётся за минуты и далее работает без участия человека:")
a("Research -> Decision -> Writing -> Evaluation -> Image -> Publishing -> Analytics -> Experience")
a("")
a("### Core Principles")
a("- Platform First: единая абстракция Publisher для всех соцсетей")
a("- AI First: LLM на каждом этапе")
a("- Workflow Driven: DAG-based пайплайны через WorkflowEngineV2")
a("- Quality First: LLM-as-a-Judge с порогом 80+")
a("- Everything Is Configurable: workflows, style profiles, prompts в БД")
a("")
a("### Supported Platforms")
a("| Platform | Status | Publisher | Method |")
a("|----------|--------|-----------|--------|")
a("| Telegram | Production | TelegramPublisher | sendMessage + sendPhoto |")
a("| VK | Production | VkPublisher | wall.post |")
a("| YouTube | Sprint 14 | YouTubePublisher | Data API v3 |")
a("| Dzen | Sprint 15 | DzenPublisher | Yandex API |")
a("| TikTok/Instagram/X | Sprint 19+ | | |")
a("")
a("---")
a("")

a("## 2. Current Status & Statistics")
a("")
a("### Production Statistics (реальные данные из БД)")
a("`")
for line in files["db_stats"].split(chr(10)):
    a(line)
a("`")
a("")
a("### Component Status")
a("- DONE: Platform Core, Research, Decision, Writing, Fact Checker, Evaluator")
a("- DONE: Workflow System, Automation Manager, Image Domain")
a("- DONE: Telegram Publisher (sendMessage + sendPhoto), VK Publisher")
a("- DONE: React Dashboard")
a("- PENDING: Sprint 12 (Monitoring), Sprint 13 (ComfyUI)")
a("")
a("### Key Metrics (Sprint 11)")
a("- VK posts: 19 (100% success)")
a("- Telegram posts with images: 1+ (message_id=191)")
a("- Avg quality score: 84.1/100")
a("- Avg image prompt: 62 chars (EN, via Ollama)")
a("- Avg image size: 43-66 KB")
a("- Image gen time: <5 sec")
a("")
a("---")
a("")

a("## 3. Architecture Overview")
a("`")
a("React Dashboard -> FastAPI -> AutomationManager -> WorkflowRuntime (DAG)")
a("  -> Jobs -> Engines -> Publishers -> DB")
a("")
a("Layers: Presentation | API | Automation | Workflow | Jobs | Engines")
a("        | Publishers | Data (ORM+PG) | Cache (Redis)")
a("`")
a("")
a("---")
a("")

a("## 4. Repository Structure")
a("`")
for line in files["file_list"].split(chr(10))[:200]:
    a(line)
a("`")
a("")
a("---")
a("")

a("## 5. Sprint History")
a("")
a("**Sprint 1 Platform Core:** Docker, FastAPI, SQLAlchemy, health checks.")
a("**Sprint 2 Research:** RSS/Google News/Reddit, dedup via nomic-embed-text.")
a("**Sprint 3 Decision:** priority scoring, duplicate detection.")
a("**Sprint 4 Writing:** WritingEngine+Ollama, PromptBuilder, StyleProfiles, ModelSelector.")
a("  Models: mistral-nemo:12b (main), qwen2.5-coder:7b (tech), llama3.1:8b (backup).")
a("  Prompt: SYSTEM + STYLE + RULES + <FACTS> + OUTPUT")
a("**Sprint 5 Telegram:** TelegramPublisher, sendMessage, retry, flood control (429).")
a("**Sprint 6 Analytics:** ExecutionLogORM, metrics collection.")
a("**Sprint 7 Quality:** EvaluatorEngine (LLM Judge), 5 criteria, threshold 80, revision max 3.")
a("  Scoring: overall = factual*0.25 + relevance*0.25 + engagement*0.20 + grammar*0.15 + style*0.15")
a("**Sprint 8 Workflow:** WorkflowEngineV2 (DAG), 4 templates, APScheduler.")
a("**Sprint 9 Dashboard:** React+TS, pages, axios.")
a("**Sprint 10 Workflow Designer:** React Flow, drag-and-drop.")
a("**Sprint 11 Multi-Platform + Image Domain (CURRENT):**")
a("  1. VK Integration: vk_group_id/vk_access_token, wall.post, 19 posts in club240792540")
a("  2. Image Domain: ImagePromptEngine -> ImageEngine -> AssetManager -> ImageJob -> PublishJob")
a("  3. Telegram sendPhoto: publish_photo() с data=payload, caption<=1024")
a("  4. PublishJob: uses draft_text, multi-platform dispatcher")
a("  5. StaticFiles: app.mount(\"/assets\", StaticFiles)")
a("")
a("### Critical Decisions Sprint 11")
a("- Короткие EN промпты (<100 chars) - иначе Pollinations 0 bytes при URL>200")
a("- data=payload вместо json=payload для Telegram sendPhoto")
a("- extra_data = Column(\"metadata\", JSON) - SQLAlchemy резервирует metadata")
a("- host.docker.internal:11434 для Ollama из контейнера")
a("- Retry 3 попытки backoff 2.0 в AssetManager")
a("")
a("---")
a("")

a("## 6. Real Code: Engines")
a("")
code("6.1 TelegramPublisher LOW-LEVEL (engines/telegram/publisher.py)", "telegram_publisher")
a("**Key:** publish_photo() uses data=payload (NOT json!), caption<=1024, fallback to text.")
a("")
code("6.2 ImagePromptEngine (engines/image_prompt/engine.py)", "image_prompt_engine")
a("**Key:** короткие EN промпты <100 chars через Ollama mistral-nemo:12b.")
a("Критично: иначе Pollinations URL>200 -> 0 bytes. Fallback: 'anime scene, high quality'")
a("")
code("6.3 ImageEngine (engines/image/engine.py)", "image_engine")
a("**Key:** URL = https://image.pollinations.ai/prompt/{encoded}?width=1024&height=576&model=flux&nologo=true")
a("")
code("6.4 AssetManager (engines/asset/manager.py)", "asset_manager")
a("**Key:** _download_with_retry (3 попытки, backoff 2.0, timeout 120s)")
a("Validation: file_size>1KB. Saves /app/assets/YYYY/MM/uuid.png.")
a("extra_data вместо metadata. Creates AssetORM, updates content.asset_id.")
a("")
code("6.5 TelegramEngine wrapper (engines/telegram/engine.py)", "telegram_engine")
a("")
a("---")
a("")

a("## 7. Real Code: Jobs")
a("")
code("7.1 ImageJob (backend/automation/jobs/image_job.py)", "image_job")
a("**Key:** approved posts без image_url (limit 10) -> ImageEngine -> image_url/image_prompt.")
a("")
code("7.2 Jobs Registry (backend/automation/jobs/__init__.py)", "jobs_init")
a("**ВАЖНО:** все 8 классов экспортируются - не удалять!")
a("")
a("---")
a("")

a("## 8. Real Code: Publishers")
a("")
code("8.1 TelegramPublisher automation layer (backend/automation/publishers/telegram.py)", "auto_telegram_pub")
a("**Key:** wrapper over engines.telegram.publisher, принимает image_url через kwargs.")
a("")
code("8.2 VkPublisher (backend/automation/publishers/vk.py)", "vk_publisher")
a("**Key:** wall.post, vk_group_id (negative), vk_access_token, v=5.199")
a("")
a("---")
a("")

a("## 9. Real Code: Runner (Workflow)")
a("")
code("9.1 AutomationRunner (backend/automation/runner.py)", "runner")
a("**Key:** stage_map (stage_name -> Job), node_type_to_job (с алиасами),")
a("run_now() с fallback jobs list: research->decision->writing->evaluation->publish.")
a("")
a("---")
a("")

a("## 10. Real Code: ORM Models")
a("")
code("10.1 AssetORM (core/models/asset_orm.py)", "asset_orm")
a("**ВАЖНО:** extra_data = Column(\"metadata\", JSON) - SQLAlchemy резервирует metadata.")
a("")
code("10.2 ContentORM (core/models/content_orm.py)", "content_orm")
a("**Key:** image_url, image_prompt, asset_id FK, status lifecycle.")
a("")
code("10.3 ChannelORM (core/models/channel_orm.py)", "channel_orm")
a("**Key:** Telegram (bot_token, chat_id), VK (vk_group_id, vk_access_token), sources JSON.")
a("")
a("---")
a("")

a("## 11. Image Domain Pipeline (полный поток)")
a("`")
a("Content (status=approved, image_url=None)")
a("  -> ImageJob.run()")
a("  -> ImagePromptEngine.generate_prompt(headline, draft_text)")
a("     # Ollama переводит RU -> EN, короткие промпты <100 chars")
a("     -> image_prompt (EN, avg 62 chars)")
a("  -> ImageEngine.generate(prompt)")
a("     -> image_url (avg 168 chars)")
a("  -> AssetManager.save_from_url(image_url)")
a("     # Download + retry (3 попытки) + save to /app/assets/")
a("     -> asset (AssetORM)")
a("  -> Content.image_url = image_url")
a("  -> Content.asset_id = asset.id")
a("  -> PublishJob.run()")
a("  -> TelegramPublisher.publish(text, image_url, credentials)")
a("  -> POST https://api.telegram.org/bot{token}/sendPhoto")
a("     data={  # ВАЖНО: data=, не json=")
a("       \"chat_id\": chat_id,")
a("       \"photo\": image_url,")
a("       \"caption\": text[:1024]")
a("     }")
a("  -> Post с картинкой в Telegram")
a("`")
a("")
a("---")
a("")

a("## 12. Database Schema")
a("")
a("### channels")
a("| Column | Type | Note |")
a("|--------|------|------|")
a("| id | VARCHAR PK | UUID |")
a("| name | VARCHAR | |")
a("| platform | VARCHAR | telegram/vk/youtube/dzen |")
a("| bot_token, chat_id | VARCHAR | Telegram |")
a("| vk_group_id, vk_access_token | VARCHAR | VK |")
a("| is_connected, is_active | BOOLEAN | |")
a("| style_profile, language_publish | VARCHAR | |")
a("| workflow_id | VARCHAR FK | |")
a("| sources | JSON | KnowledgeSource[] |")
a("")
a("### content")
a("| Column | Type | Note |")
a("|--------|------|------|")
a("| id | VARCHAR PK | |")
a("| channel_id | VARCHAR FK | |")
a("| source_url | VARCHAR NOT NULL | |")
a("| headline, source_text | TEXT | |")
a("| status | VARCHAR | research/draft/needs_revision/approved/published/rejected |")
a("| draft_text | TEXT | generated |")
a("| quality_score | INTEGER | 0-100 |")
a("| image_url | VARCHAR(500) | Pollinations |")
a("| image_prompt | TEXT | prompt used |")
a("| asset_id | VARCHAR FK | -> assets |")
a("| telegram_message_id | VARCHAR | |")
a("| published_at | TIMESTAMP | |")
a("")
a("### assets")
a("| Column | Type | Note |")
a("|--------|------|------|")
a("| id | VARCHAR PK | |")
a("| content_id | VARCHAR FK | |")
a("| type | VARCHAR | image/video/audio |")
a("| storage_path | VARCHAR | assets/2026/08/uuid.png |")
a("| public_url | VARCHAR | /assets/... |")
a("| prompt, model | VARCHAR/TEXT | |")
a("| seed, width, height | INTEGER | |")
a("| generation_time_ms | INTEGER | |")
a("| status | VARCHAR | generating/generated/failed |")
a("| extra_data | JSON | maps to \"metadata\" column |")
a("")
a("### Production Stats")
a("`")
for line in files["db_stats"].split(chr(10)):
    a(line)
a("`")
a("")
a("---")
a("")

a("## 13. Workflow Templates")
a("`")
for line in files["workflows"].split(chr(10)):
    a(line)
a("`")
a("")
a("Presets: Simple | Default Full | Research Only | Legacy")
a("")
a("---")
a("")

a("## 14. API Endpoints")
a("### Channels")
a("- GET /api/v1/channels")
a("- POST /api/v1/channels")
a("- GET/PATCH/DELETE /api/v1/channels/{id}")
a("- POST /api/v1/channels/{id}/connect-telegram")
a("- POST /api/v1/channels/{id}/connect-vk")
a("- PUT /api/v1/channels/{id}/schedule")
a("### Content")
a("- GET /api/v1/content?channel_id=&status=")
a("- PATCH /api/v1/content/{id}")
a("### Workflows")
a("- GET /api/v1/workflows")
a("- POST /api/v1/workflows/{id}/run")
a("### Other")
a("- GET /health")
a("- GET /assets/... (StaticFiles)")
a("- GET /api/v1/logs")
a("")
a("---")
a("")

a("## 15. Configuration")
a("### docker-compose.yml")
a("`yaml")
for line in files["docker_compose"].split(chr(10)):
    a(line)
a("`")
a("")
a("### Environment")
a("- DATABASE_URL: postgresql://amf_user:amf_password@postgres:5432/ai_media_factory")
a("- REDIS_URL: redis://redis:6379")
a("- OLLAMA_BASE_URL: http://host.docker.internal:11434")
a("- VK_API_VERSION: 5.199")
a("")
a("### LLM Models (Ollama)")
a("- mistral-nemo:12b (main writing + prompts)")
a("- llama3.1:8b, gemma2:9b (alternatives)")
a("- qwen2.5-coder:7b (tech)")
a("- nomic-embed-text (embeddings)")
a("")
a("---")
a("")

a("## 16. Main Application")
a("")
code("FastAPI app (backend/main.py)", "main_py")
a("**ВАЖНО:** app.mount(\"/assets\", StaticFiles(directory=\"/app/assets\")) для доступа к картинкам.")
a("")
a("---")
a("")

a("## 17. Known Issues & Solutions")
a("")
a("| # | Problem | Solution |")
a("|---|---------|----------|")
a("| 1 | Pollinations 0 bytes at URL>200 | Короткие EN промпты <100 chars через Ollama |")
a("| 2 | Telegram sendPhoto 400 | data=payload вместо json=payload |")
a("| 3 | SQLAlchemy metadata reserved | extra_data = Column(\"metadata\", JSON) |")
a("| 4 | Ollama недоступен из контейнера | host.docker.internal:11434 |")
a("| 5 | ContentORM ломается патчами | py_compile.validate + show diff |")
a("| 6 | RevisionJob/ReEvaluationJob удалены случайно | импорты в __init__.py и runner.py |")
a("| 7 | Assets не персистентны | TODO: volume ./assets:/app/assets |")
a("| 8 | Нет image validation | TODO Sprint 13: ImageValidator |")
a("| 9 | PowerShell Invoke-WebRequest | -UseBasicParsing |")
a("| 10 | xargs/grep недоступны в PS | Select-String/Select-Object |")
a("| 11 | Telegram caption>1024 | Автообрезка с ... |")
a("| 12 | Пустые файлы Pollinations | file_size>1KB в AssetManager |")
a("")
a("### Coding Standards")
a("- Engines: чистая бизнес-логика, без FastAPI")
a("- Jobs: тонкая обёртка над Engines, логирование")
a("- Publishers: credentials validation, retry, fallback")
a("- ORM: nullable=True кроме PK, FK с ondelete")
a("- API: только вызовы repositories/engines")
a("- Патчи: Python-скрипт + py_compile")
a("- PowerShell: single-quoted here-strings, -UseBasicParsing")
a("")
a("---")
a("")

a("## 18. Roadmap")
a("### Sprint 12: Monitoring & Alerting (NEXT)")
a("- [ ] Telegram bot уведомлений")
a("- [ ] Health checks (Ollama, Pollinations, VK, Telegram)")
a("- [ ] SLA metrics, Grafana")
a("- [ ] Alerting: 5xx, low quality, API failures")
a("")
a("### Sprint 13: ComfyUI Integration")
a("- [ ] Local ComfyUI Docker")
a("- [ ] Flux/SDXL модели")
a("- [ ] ImageValidator (LLM score)")
a("- [ ] A/B testing картинок")
a("- [ ] Volume ./assets:/app/assets")
a("")
a("### Sprint 14: YouTube Shorts")
a("- [ ] YouTube Data API v3, OAuth2")
a("- [ ] Vertical 9:16, auto-thumbnail")
a("")
a("### Sprint 15: Dzen Publishing")
a("### Sprint 16: Experience Engine (engagement, learning loop)")
a("### Sprint 17: Workflow Designer v2 (conditional branching)")
a("### Sprint 18: Marketplace (public templates)")
a("### Sprint 19-25: TikTok/Instagram/X, realtime analytics, SaaS")
a("")
a("---")
a("")

a("## 19. Appendix")
a("")
a("### Production URLs")
a("| Service | URL |")
a("|---------|-----|")
a("| React Dashboard | http://localhost:3000 |")
a("| API docs | http://localhost:8000/docs |")
a("| API v1 | http://localhost:8000/api/v1 |")
a("| Health | http://localhost:8000/health |")
a("| Assets | http://localhost:8000/assets/... |")
a("| PostgreSQL | localhost:5432 (amf_user / ai_media_factory) |")
a("| Redis | localhost:6379 |")
a("| Ollama | http://localhost:11434 |")
a("")
a("### Test Channels")
a("- Telegram AI Anime News: chat_id=-1003901198631, wf-simple")
a("- Telegram AI News: inactive")
a("- Telegram AI News RU (Test): chat_id=-1004324099845, inactive")
a("- Test VK Channel: vk_group_id=-240792540")
a("")
a("### CHANGELOG")
a("- v0.1-v1.10: internal development")
a("- **v1.11 (Sprint 11)**: VK Publisher + Image Domain + Telegram sendPhoto")
a("- v1.12 (planned): Monitoring & Alerting")
a("")
a("---")
a("**End of Document**")
a("Generated: 2026-08-11 | Sprint 11 Complete")

Path("docs").mkdir(exist_ok=True)
out = Path("docs/MASTER_DOCUMENTATION_EXTENDED.md")
out.write_text(chr(10).join(L), encoding="utf-8")
size_kb = out.stat().st_size / 1024
lines_count = len(L)
print("=" * 60)
print("EXTENDED MASTER DOCUMENTATION CREATED")
print("=" * 60)
print(f"  Path: {out}")
print(f"  Size: {size_kb:.1f} KB")
print(f"  Lines: {lines_count}")
print("=" * 60)
